global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:

  # Monitor Prometheus sendiri
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  # Monitor semua node exporter
  - job_name: 'nodes'
    static_configs:
      - targets:
          - 'localhost:9100'
          - '52.53.252.250:9100'
          - '18.142.47.197:9100'
          - '3.66.155.203:9100'
          - '35.183.136.44:9100'
        labels:
          layer: 'infrastructure'
          cluster: 'raft-exp'

  # Monitor raft cluster
  - job_name: 'raft-cluster'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'localhost:9200'
          - '52.53.252.250:9200'
          - '18.142.47.197:9200'
        labels:
          layer: 'application'
          cluster: 'adaptive-raft'